"""Storage abstraction for uploaded documents.

Route handlers and `DocumentService` depend on the `StorageService` protocol, never
on the filesystem. Swapping in S3, R2 or Supabase Storage in a later phase means
adding one class here and changing the factory at the bottom — no route changes.

The stored key is opaque to everything above this module.
"""

import shutil
import uuid
from abc import ABC, abstractmethod
from pathlib import Path
from typing import BinaryIO

from app.core.config import settings
from app.core.exceptions import StorageError

# Resolves relative UPLOAD_DIR values against the backend package root, so the
# location does not depend on the process's working directory.
_BACKEND_ROOT = Path(__file__).resolve().parents[2]


def build_storage_key(course_id: uuid.UUID, extension: str) -> str:
    """A generated key — the user's filename never touches the filesystem.

    Original names can contain path separators, `..`, control characters or names
    that collide; only the extension is carried over, and it comes from a
    validated allow-list rather than from the upload.
    """
    return f"{course_id}/{uuid.uuid4().hex}.{extension.lower().lstrip('.')}"


class StorageService(ABC):
    """The interface document code is written against."""

    @abstractmethod
    def save(self, key: str, source: BinaryIO) -> None:
        """Persist `source` under `key`, replacing anything already there."""

    @abstractmethod
    def delete(self, key: str) -> None:
        """Remove `key`. Succeeds silently when it is already gone."""

    @abstractmethod
    def get_path(self, key: str) -> Path:
        """Local filesystem path for `key`.

        Only meaningful for backends that have one. Phase 3's text extraction is the
        first real caller; an object-store backend will download to a temp file.
        """

    @abstractmethod
    def exists(self, key: str) -> bool:
        """Whether `key` is present in the backend."""


class LocalStorageService(StorageService):
    """Filesystem-backed storage for local development."""

    def __init__(self, root: Path | None = None) -> None:
        configured = Path(settings.UPLOAD_DIR)
        base = root or (
            configured if configured.is_absolute() else _BACKEND_ROOT / configured
        )
        self.root = base
        self.root.mkdir(parents=True, exist_ok=True)

    def _resolve(self, key: str) -> Path:
        """Resolve `key` under the root, refusing anything that escapes it.

        Keys are generated by `build_storage_key`, but this stays defence in depth:
        a traversal bug elsewhere must not become an arbitrary-file-write bug.
        """
        candidate = (self.root / key).resolve()
        if not candidate.is_relative_to(self.root.resolve()):
            raise StorageError("Refusing to access a path outside the storage root.")
        return candidate

    def save(self, key: str, source: BinaryIO) -> None:
        destination = self._resolve(key)
        destination.parent.mkdir(parents=True, exist_ok=True)
        try:
            with destination.open("wb") as target:
                shutil.copyfileobj(source, target)
        except OSError as error:
            raise StorageError() from error

    def delete(self, key: str) -> None:
        try:
            self._resolve(key).unlink(missing_ok=True)
        except OSError as error:
            raise StorageError("The file could not be removed.") from error

    def get_path(self, key: str) -> Path:
        return self._resolve(key)

    def exists(self, key: str) -> bool:
        return self._resolve(key).is_file()


def get_storage_service() -> StorageService:
    """Factory. The place to branch on a STORAGE_BACKEND setting in a later phase."""
    return LocalStorageService()
