"""Retention: mastery history, spaced repetition, exam date.

Adds the Phase 5 schema:

    mastery_events          event-sourced history of every mastery change
    flashcard_review_states scheduling state, keyed by (user, card)
    flashcard_reviews       one immutable row per rating given
    courses.exam_date       optional; drives Exam Prep
    topic_mastery.flashcard_reviews  weaker, self-reported evidence, counted apart

Nothing here decays anything. Stored mastery remains exactly what the student
demonstrated; effective mastery is derived on read in
`app/services/learning/retention.py`. There is deliberately no scheduled job that
subtracts points as time passes.

Revision ID: 2cf565e0f3bd
Revises: 546e7760abfa
Create Date: 2026-08-28 17:33:30.752585

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cf565e0f3bd"
down_revision: str | Sequence[str] | None = "546e7760abfa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mastery_events",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "QUIZ_ANSWER",
                "FLASHCARD_REVIEW",
                name="mastery_event_source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("previous_raw_score", sa.Float(), nullable=False),
        sa.Column("new_raw_score", sa.Float(), nullable=False),
        sa.Column("previous_mastery", sa.Float(), nullable=False),
        sa.Column("new_mastery", sa.Float(), nullable=False),
        sa.Column("effective_mastery_at_event", sa.Float(), nullable=False),
        sa.Column("was_correct", sa.Boolean(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum("EASY", "MEDIUM", "HARD", name="difficulty", native_enum=False),
            nullable=True,
        ),
        sa.Column("questions_attempted_after", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_mastery_events_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_mastery_events_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_mastery_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mastery_events")),
    )
    op.create_index(
        "ix_mastery_events_course_time",
        "mastery_events",
        ["user_id", "course_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_mastery_events_topic_time",
        "mastery_events",
        ["user_id", "topic_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "flashcard_review_states",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("flashcard_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("ease", sa.Float(), nullable=False),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ease >= 1.0 AND ease <= 3.5",
            name=op.f("ck_flashcard_review_states_ease_range"),
        ),
        sa.CheckConstraint(
            "interval_days >= 0",
            name=op.f("ck_flashcard_review_states_interval_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_flashcard_review_states_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flashcard_id"],
            ["flashcards.id"],
            name=op.f("fk_flashcard_review_states_flashcard_id_flashcards"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_flashcard_review_states_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_flashcard_review_states_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flashcard_review_states")),
        sa.UniqueConstraint("user_id", "flashcard_id", name="uq_review_state_user_card"),
    )
    op.create_index(
        op.f("ix_flashcard_review_states_topic_id"),
        "flashcard_review_states",
        ["topic_id"],
        unique=False,
    )
    op.create_index(
        "ix_review_states_due",
        "flashcard_review_states",
        ["user_id", "course_id", "due_at"],
        unique=False,
    )
    op.create_table(
        "flashcard_reviews",
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "rating",
            sa.Enum(
                "AGAIN", "HARD", "GOOD", "EASY", name="review_rating", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("interval_days_after", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["flashcard_review_states.id"],
            name=op.f("fk_flashcard_reviews_state_id_flashcard_review_states"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_flashcard_reviews_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flashcard_reviews")),
    )
    op.create_index(
        op.f("ix_flashcard_reviews_state_id"),
        "flashcard_reviews",
        ["state_id"],
        unique=False,
    )
    op.create_index(
        "ix_flashcard_reviews_user_time",
        "flashcard_reviews",
        ["user_id", "reviewed_at"],
        unique=False,
    )
    op.add_column("courses", sa.Column("exam_date", sa.Date(), nullable=True))
    # server_default is required, not cosmetic: without it this ALTER fails on any
    # database that already has topic_mastery rows.
    op.add_column(
        "topic_mastery",
        sa.Column("flashcard_reviews", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic_mastery", "flashcard_reviews")
    op.drop_column("courses", "exam_date")
    op.drop_index("ix_flashcard_reviews_user_time", table_name="flashcard_reviews")
    op.drop_index(op.f("ix_flashcard_reviews_state_id"), table_name="flashcard_reviews")
    op.drop_table("flashcard_reviews")
    op.drop_index("ix_review_states_due", table_name="flashcard_review_states")
    op.drop_index(
        op.f("ix_flashcard_review_states_topic_id"), table_name="flashcard_review_states"
    )
    op.drop_table("flashcard_review_states")
    op.drop_index("ix_mastery_events_topic_time", table_name="mastery_events")
    op.drop_index("ix_mastery_events_course_time", table_name="mastery_events")
    op.drop_table("mastery_events")
    # ### end Alembic commands ###
