"""Adaptive learning: topics, quizzes, attempts, mastery, flashcards.

Adds the Phase 4 schema:

    topics          concepts derived from a course's own material
    topic_mastery   one student's demonstrated command of one topic
    quizzes         a generated question set, persisted so refreshes are free
    quiz_questions  MCQ + provenance FKs to the chunk it came from
    quiz_attempts   one run through a quiz
    quiz_answers    one answer within an attempt

DROPS `study_progress`. That Phase 1 table keyed mastery to a free-text topic name
on a 0-1 scale and was never written to — its service raised 501 and the endpoints
were placeholders. `topic_mastery` supersedes it with a real Topic foreign key and a
0-100 score. Keeping both would leave two competing sources of truth for the same
concept.

Revision ID: 546e7760abfa
Revises: c1f83d5a47b2
Create Date: 2026-08-28 15:14:40.468641

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "546e7760abfa"
down_revision: str | Sequence[str] | None = "c1f83d5a47b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quizzes",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("STANDARD", "ADAPTIVE", name="quiz_mode", native_enum=False),
            nullable=False,
        ),
        sa.Column("selection_rationale", sa.Text(), nullable=False),
        sa.Column(
            "difficulty_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_quizzes_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_quizzes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quizzes")),
    )
    op.create_index(
        "ix_quizzes_course_id_created_at",
        "quizzes",
        ["course_id", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_quizzes_user_id"), "quizzes", ["user_id"], unique=False)
    op.create_table(
        "topics",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("normalised_name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_topics_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
        sa.UniqueConstraint("course_id", "normalised_name", name="uq_topics_course_name"),
    )
    op.create_index(
        "ix_topics_course_id_is_active",
        "topics",
        ["course_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "quiz_attempts",
        sa.Column("quiz_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score_percent", sa.Float(), nullable=True),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "score_percent IS NULL OR (score_percent >= 0 AND score_percent <= 100)",
            name=op.f("ck_quiz_attempts_score_percent_range"),
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_quiz_attempts_quiz_id_quizzes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_quiz_attempts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_attempts")),
    )
    op.create_index(
        op.f("ix_quiz_attempts_quiz_id"), "quiz_attempts", ["quiz_id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_attempts_user_id"), "quiz_attempts", ["user_id"], unique=False
    )
    op.create_table(
        "topic_mastery",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("mastery_score", sa.Float(), nullable=False),
        sa.Column("raw_score", sa.Float(), nullable=False),
        sa.Column("questions_attempted", sa.Integer(), nullable=False),
        sa.Column("correct_answers", sa.Integer(), nullable=False),
        sa.Column("last_answer_correct", sa.Boolean(), nullable=True),
        sa.Column("last_practised_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "correct_answers >= 0 AND correct_answers <= questions_attempted",
            name=op.f("ck_topic_mastery_correct_within_attempted"),
        ),
        sa.CheckConstraint(
            "mastery_score >= 0 AND mastery_score <= 100",
            name=op.f("ck_topic_mastery_mastery_score_range"),
        ),
        sa.CheckConstraint(
            "raw_score >= 0 AND raw_score <= 100",
            name=op.f("ck_topic_mastery_raw_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_topic_mastery_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_topic_mastery_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_topic_mastery_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_mastery")),
        sa.UniqueConstraint("user_id", "topic_id", name="uq_topic_mastery_user_topic"),
    )
    op.create_index(
        op.f("ix_topic_mastery_course_id"), "topic_mastery", ["course_id"], unique=False
    )
    op.create_index(
        op.f("ix_topic_mastery_topic_id"), "topic_mastery", ["topic_id"], unique=False
    )
    op.create_index(
        op.f("ix_topic_mastery_user_id"), "topic_mastery", ["user_id"], unique=False
    )
    op.create_table(
        "flashcards",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("front", sa.Text(), nullable=False),
        sa.Column("back", sa.Text(), nullable=False),
        sa.Column("source_chunk_id", sa.Uuid(), nullable=True),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_flashcards_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_flashcards_source_chunk_id_document_chunks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
            name=op.f("fk_flashcards_source_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_flashcards_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_flashcards_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flashcards")),
    )
    op.create_index(
        op.f("ix_flashcards_topic_id"), "flashcards", ["topic_id"], unique=False
    )
    op.create_index(
        "ix_flashcards_user_course", "flashcards", ["user_id", "course_id"], unique=False
    )
    op.create_table(
        "quiz_questions",
        sa.Column("quiz_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correct_index", sa.Integer(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("EASY", "MEDIUM", "HARD", name="difficulty", native_enum=False),
            nullable=False,
        ),
        sa.Column("source_chunk_id", sa.Uuid(), nullable=True),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_quiz_questions_quiz_id_quizzes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_quiz_questions_source_chunk_id_document_chunks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
            name=op.f("fk_quiz_questions_source_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_quiz_questions_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_questions")),
    )
    op.create_index(
        op.f("ix_quiz_questions_quiz_id"), "quiz_questions", ["quiz_id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_questions_topic_id"), "quiz_questions", ["topic_id"], unique=False
    )
    op.create_table(
        "quiz_answers",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("selected_index", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("answered_in_seconds", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["quiz_attempts.id"],
            name=op.f("fk_quiz_answers_attempt_id_quiz_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["quiz_questions.id"],
            name=op.f("fk_quiz_answers_question_id_quiz_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_answers")),
        sa.UniqueConstraint(
            "attempt_id", "question_id", name="uq_quiz_answers_attempt_q"
        ),
    )
    op.create_index(
        op.f("ix_quiz_answers_attempt_id"), "quiz_answers", ["attempt_id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_answers_question_id"), "quiz_answers", ["question_id"], unique=False
    )
    op.drop_index(op.f("ix_study_progress_course_id"), table_name="study_progress")
    op.drop_index(op.f("ix_study_progress_user_id"), table_name="study_progress")
    op.drop_table("study_progress")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_progress",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("course_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("topic", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column(
            "mastery_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.CheckConstraint(
            "mastery_score >= 0::double precision "
            "AND mastery_score <= 1::double precision",
            name=op.f("ck_study_progress_mastery_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_study_progress_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_study_progress_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_progress")),
        sa.UniqueConstraint(
            "user_id",
            "course_id",
            "topic",
            name=op.f("uq_study_progress_user_id_course_topic"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_study_progress_user_id"), "study_progress", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_study_progress_course_id"), "study_progress", ["course_id"], unique=False
    )
    op.drop_index(op.f("ix_quiz_answers_question_id"), table_name="quiz_answers")
    op.drop_index(op.f("ix_quiz_answers_attempt_id"), table_name="quiz_answers")
    op.drop_table("quiz_answers")
    op.drop_index(op.f("ix_quiz_questions_topic_id"), table_name="quiz_questions")
    op.drop_index(op.f("ix_quiz_questions_quiz_id"), table_name="quiz_questions")
    op.drop_table("quiz_questions")
    op.drop_index("ix_flashcards_user_course", table_name="flashcards")
    op.drop_index(op.f("ix_flashcards_topic_id"), table_name="flashcards")
    op.drop_table("flashcards")
    op.drop_index(op.f("ix_topic_mastery_user_id"), table_name="topic_mastery")
    op.drop_index(op.f("ix_topic_mastery_topic_id"), table_name="topic_mastery")
    op.drop_index(op.f("ix_topic_mastery_course_id"), table_name="topic_mastery")
    op.drop_table("topic_mastery")
    op.drop_index(op.f("ix_quiz_attempts_user_id"), table_name="quiz_attempts")
    op.drop_index(op.f("ix_quiz_attempts_quiz_id"), table_name="quiz_attempts")
    op.drop_table("quiz_attempts")
    op.drop_index("ix_topics_course_id_is_active", table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_quizzes_user_id"), table_name="quizzes")
    op.drop_index("ix_quizzes_course_id_created_at", table_name="quizzes")
    op.drop_table("quizzes")
    # ### end Alembic commands ###
