"""Knowledge map, short answer, study guide, user timezone.

Adds the Phase 6 schema:

    topic_relationships           inferred prerequisite / related edges
    topic_relationship_evidence   the chunks supporting each edge
    study_guides                  persisted grounded guide, with a stale marker
    study_guide_sections          one per topic
    study_guide_section_sources   provenance for each section
    users.timezone                IANA identifier, existing rows default to UTC

And extends quizzes for short answers WITHOUT disturbing existing MCQ rows:

    quiz_questions.question_type  defaults to MCQ, so every existing row is correct
    quiz_questions.options        relaxed to NULL (short answers have none)
    quiz_questions.correct_index  relaxed to NULL
    quiz_answers.selected_index   relaxed to NULL
    quiz_answers.is_correct       relaxed to NULL — an `uncertain` verdict is
                                  neither true nor false, and forcing a boolean
                                  would lose that distinction

Relaxing NOT NULL is safe in both directions for existing data: every MCQ row
already has values. The downgrade cannot restore NOT NULL without deleting
short-answer rows, so it clears them first — noted there explicitly.

Revision ID: 79c070ce1535
Revises: 2cf565e0f3bd
Create Date: 2026-08-29 14:01:53.645847

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '79c070ce1535'
down_revision: str | Sequence[str] | None = '2cf565e0f3bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_guides',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NOT_GENERATED', 'GENERATING', 'READY', 'STALE', 'FAILED', name='study_guide_status', native_enum=False), server_default='NOT_GENERATED', nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('key_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('material_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_study_guides_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_guides_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_guides')),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_study_guide_user_course')
    )
    op.create_table('study_guide_sections',
    sa.Column('guide_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['study_guides.id'], name=op.f('fk_study_guide_sections_guide_id_study_guides'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_study_guide_sections_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_guide_sections'))
    )
    op.create_index('ix_study_guide_sections_guide', 'study_guide_sections', ['guide_id', 'position'], unique=False)
    op.create_index(op.f('ix_study_guide_sections_topic_id'), 'study_guide_sections', ['topic_id'], unique=False)
    op.create_table('topic_relationships',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('source_topic_id', sa.Uuid(), nullable=False),
    sa.Column('target_topic_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Enum('PREREQUISITE', 'RELATED', name='relationship_type', native_enum=False), nullable=False),
    sa.Column('supporting_chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_topic_id <> target_topic_id', name=op.f('ck_topic_relationships_no_self_edge')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_topic_relationships_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_topic_id'], ['topics.id'], name=op.f('fk_topic_relationships_source_topic_id_topics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_topic_id'], ['topics.id'], name=op.f('fk_topic_relationships_target_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_relationships')),
    sa.UniqueConstraint('source_topic_id', 'target_topic_id', 'relationship_type', name='uq_topic_relationship_pair')
    )
    op.create_index('ix_topic_relationships_course_type', 'topic_relationships', ['course_id', 'relationship_type'], unique=False)
    op.create_index(op.f('ix_topic_relationships_source_topic_id'), 'topic_relationships', ['source_topic_id'], unique=False)
    op.create_index('ix_topic_relationships_target', 'topic_relationships', ['target_topic_id'], unique=False)
    op.create_table('study_guide_section_sources',
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('fk_study_guide_section_sources_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_study_guide_section_sources_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['study_guide_sections.id'], name=op.f('fk_study_guide_section_sources_section_id_study_guide_sections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_guide_section_sources')),
    sa.UniqueConstraint('section_id', 'chunk_id', name='uq_section_source_chunk')
    )
    op.create_index(op.f('ix_study_guide_section_sources_section_id'), 'study_guide_section_sources', ['section_id'], unique=False)
    op.create_table('topic_relationship_evidence',
    sa.Column('relationship_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('fk_topic_relationship_evidence_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_topic_relationship_evidence_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['topic_relationships.id'], name=op.f('fk_topic_relationship_evidence_relationship_id_topic_relationships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_relationship_evidence')),
    sa.UniqueConstraint('relationship_id', 'chunk_id', name='uq_relationship_evidence_chunk')
    )
    op.create_index(op.f('ix_topic_relationship_evidence_relationship_id'), 'topic_relationship_evidence', ['relationship_id'], unique=False)
    op.add_column('quiz_answers', sa.Column('response_text', sa.Text(), nullable=True))
    op.add_column('quiz_answers', sa.Column('verdict', sa.Enum('CORRECT', 'PARTIALLY_CORRECT', 'INCORRECT', 'UNCERTAIN', name='answer_verdict', native_enum=False), nullable=True))
    op.add_column('quiz_answers', sa.Column('rubric_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quiz_answers', sa.Column('feedback', sa.Text(), nullable=True))
    op.add_column('quiz_answers', sa.Column('grading_state', sa.Enum('NOT_REQUIRED', 'GRADED', 'FAILED', name='grading_state', native_enum=False), server_default='NOT_REQUIRED', nullable=False))
    op.add_column('quiz_answers', sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quiz_answers', sa.Column('grader_model', sa.String(length=120), nullable=True))
    op.alter_column('quiz_answers', 'selected_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('quiz_questions', sa.Column('question_type', sa.Enum('MCQ', 'SHORT_ANSWER', name='question_type', native_enum=False), server_default='MCQ', nullable=False))
    op.add_column('quiz_questions', sa.Column('reference_answer', sa.Text(), nullable=True))
    op.add_column('quiz_questions', sa.Column('key_concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quiz_questions', sa.Column('rubric', sa.Text(), nullable=True))
    op.alter_column('quiz_questions', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('quiz_questions', 'correct_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Restoring NOT NULL on the MCQ columns is only possible if no short-answer rows
    exist, so they are removed first. This is destructive and deliberate: a
    pre-Phase-6 schema has nowhere to put a short answer, and leaving the rows would
    make the ALTER fail rather than the data survive. MCQ questions and answers are
    untouched.
    """
    op.execute(
        """
        DELETE FROM quiz_answers
         WHERE question_id IN (
               SELECT id FROM quiz_questions WHERE question_type = 'SHORT_ANSWER'
         )
        """
    )
    op.execute("DELETE FROM quiz_questions WHERE question_type = 'SHORT_ANSWER'")
    # An `uncertain` verdict left is_correct null on an MCQ row only if a future
    # change allowed it; guard anyway so the ALTER cannot fail.
    op.execute("DELETE FROM quiz_answers WHERE selected_index IS NULL OR is_correct IS NULL")

    op.drop_column('users', 'timezone')
    op.alter_column('quiz_questions', 'correct_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quiz_questions', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('quiz_questions', 'rubric')
    op.drop_column('quiz_questions', 'key_concepts')
    op.drop_column('quiz_questions', 'reference_answer')
    op.drop_column('quiz_questions', 'question_type')
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('quiz_answers', 'selected_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('quiz_answers', 'grader_model')
    op.drop_column('quiz_answers', 'graded_at')
    op.drop_column('quiz_answers', 'grading_state')
    op.drop_column('quiz_answers', 'feedback')
    op.drop_column('quiz_answers', 'rubric_results')
    op.drop_column('quiz_answers', 'verdict')
    op.drop_column('quiz_answers', 'response_text')
    op.drop_index(op.f('ix_topic_relationship_evidence_relationship_id'), table_name='topic_relationship_evidence')
    op.drop_table('topic_relationship_evidence')
    op.drop_index(op.f('ix_study_guide_section_sources_section_id'), table_name='study_guide_section_sources')
    op.drop_table('study_guide_section_sources')
    op.drop_index('ix_topic_relationships_target', table_name='topic_relationships')
    op.drop_index(op.f('ix_topic_relationships_source_topic_id'), table_name='topic_relationships')
    op.drop_index('ix_topic_relationships_course_type', table_name='topic_relationships')
    op.drop_table('topic_relationships')
    op.drop_index(op.f('ix_study_guide_sections_topic_id'), table_name='study_guide_sections')
    op.drop_index('ix_study_guide_sections_guide', table_name='study_guide_sections')
    op.drop_table('study_guide_sections')
    op.drop_table('study_guides')
    # ### end Alembic commands ###
