"""Document chunks with pgvector embeddings.

Adds `document_chunks`, one row per retrievable slice of a document, each holding
its page number so answers can cite it, plus `documents.processing_error`.

VECTOR DIMENSION: 1536, fixed by the `text-embedding-3-small` embedding model
(app.core.config.Settings.EMBEDDING_DIMENSIONS). Vectors from different models are
not comparable, so switching models requires BOTH a migration altering this column
AND a full re-embed of every existing chunk. Do not change EMBEDDING_MODEL alone.

NO VECTOR INDEX is created. With a small corpus, PostgreSQL's sequential scan beats
an approximate index, and IVFFlat needs a populated table to build meaningful
lists. Add one once retrieval latency justifies it:

    CREATE INDEX ix_document_chunks_embedding_hnsw
        ON document_chunks USING hnsw (embedding vector_cosine_ops);

Use `vector_cosine_ops` to match the `<=>` operator retrieval.py orders by.

Revision ID: 924dcf437b93
Revises: 9c41f2b7a0e5
Create Date: 2026-08-28 10:59:41.578368

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "924dcf437b93"
down_revision: str | Sequence[str] | None = "9c41f2b7a0e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_chunks",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
    )
    op.create_index(
        "ix_document_chunks_document_id_chunk_index",
        "document_chunks",
        ["document_id", "chunk_index"],
        unique=False,
    )
    op.add_column(
        "documents", sa.Column("processing_error", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "processing_error")
    op.drop_index(
        "ix_document_chunks_document_id_chunk_index", table_name="document_chunks"
    )
    op.drop_table("document_chunks")
    # ### end Alembic commands ###
