"""Track the material a course's topics were extracted from.

Adds `courses.topics_fingerprint`: a digest of the READY documents the topic set
was last derived from. Comparing it with the course's current material is how
ANCHOR knows whether topics still reflect what has been uploaded, which is what
lets extraction run automatically after processing instead of being a manual step
the student has to know about.

Existing rows default to the empty string, meaning "never recorded". That is
deliberate rather than backfilled with the current digest: a course whose
documents changed before this column existed genuinely is out of sync, and
assuming otherwise would hide it. The sync check treats a course with no READY
material as current regardless, so an empty course never asks to be updated.

Revision ID: b3a0f1279167
Revises: 79c070ce1535
Create Date: 2026-09-01 20:13:13.013241

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3a0f1279167"
down_revision: str | Sequence[str] | None = "79c070ce1535"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required, not cosmetic: courses already has rows, and a
    # NOT NULL column without one fails the ALTER on any populated database.
    op.add_column(
        "courses",
        sa.Column(
            "topics_fingerprint",
            sa.String(length=64),
            server_default="",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "topics_fingerprint")
    # ### end Alembic commands ###
